#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        return(a / 2)
    except NameError:
        print(message)
